export const GET_CONTACTS = "GET_CONTACTS";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
export const NEXT_CONTACTS = "NEXT_CONTACTS"
export const DYSPLAY_MODAL = "DYSPLAY_MODAL"
export const CHANGE_PAGE = "CHANGE_PAGE";
